import numtan as nt


EXPECTED = {
    "adaptive_rk4",
    "add",
    "atanint",
    "complex_tan",
    "convolve",
    "correlation",
    "covariance",
    "dot",
    "euler",
    "exponential_smooth",
    "finite_difference",
    "find_peaks",
    "gauss_newton",
    "gradient",
    "gradient_descent",
    "halley",
    "householder",
    "lagrange_interpolate",
    "linear_interpolate",
    "linear_regression",
    "linspace",
    "mat_vec",
    "mean",
    "midpoint",
    "moving_average",
    "newton",
    "newton_animation_data",
    "norm",
    "normalize",
    "ode_direction_field",
    "polyadd",
    "polyder",
    "polyint",
    "polymul",
    "polynomial_regression",
    "polyroot",
    "polyval",
    "quad_inf",
    "rk4",
    "sample_grid",
    "scale",
    "solve",
    "stationary_newton",
    "sub",
    "summary",
    "tan_deg",
    "tan_grad",
    "tan_sinh",
    "tangent",
    "tangent_lines",
    "tangent_minimize",
    "tanh_sinh",
    "tanint",
    "tanpi",
    "variance",
}


missing = sorted(name for name in EXPECTED if not hasattr(nt, name))
assert not missing, missing
assert nt.__version__ == "1.0.0"
print("api surface ok")
